package migemo;

import java.util.Arrays;
import java.util.SortedMap;
import java.util.TreeMap;

public class RomajiConverter {

    private final static String VOWELS = "aiueon";

    public static String roma2hira(String source) {
        if (source == null) {
            return null;
        }
        if (source.isEmpty()) {
            return "";
        }
        for (int i = Math.min(3, source.length()); i > 0; i--) {
            String key = source.substring(0, i);
            int pos = Arrays.binarySearch(keys, key);
            if (pos >= 0) {
                return values[pos] + roma2hira(source.substring(i));
            }
        }
        if (source.length() >= 2 && source.charAt(0) == source.charAt(1) && !VOWELS.contains(source.substring(0, 1))) {
            // 「っ」の判定
            return "っ" + roma2hira(source.substring(1));
        } else if (source.charAt(0) == 'n') {
            // 「n(子音)」を「ん(子音)」に変換
            return "ん" + roma2hira(source.substring(1));
        } else {
            return source.charAt(0) + roma2hira(source.substring(1));
        }
    }

    public static String[] roma2hiraDubiously(String source) {
        if (source == null) {
            return null;
        }
        if (source.isEmpty()) {
            return new String[] {""};
        }
        for (int i = Math.min(3, source.length()); i > 0; i--) {
            String key = source.substring(0, i);
            int pos = Arrays.binarySearch(keys, key);
            if (pos >= 0) {
                return concat(values[pos], roma2hiraDubiously(source.substring(i)));
            }
        }
        if (source.length() >= 2 && source.charAt(0) == source.charAt(1) &&
                VOWELS.indexOf(source.charAt(0)) == -1 && Character.isLowerCase(source.charAt(0))) {
            // 「っ」の判定
            return concat("っ", roma2hiraDubiously(source.substring(1)));
        } else if (source.charAt(0) == 'n') {
            // 「n(子音)」を「ん(子音)」に変換
            return concat("ん", roma2hiraDubiously(source.substring(1)));
        } else if (source.length() <= 2) {
            String[] results = predictiveSearch(source);
            if (results.length == 0) {
                return concat(source.substring(0, 1), roma2hiraDubiously(source.substring(1)));
            } else {
                if (Character.isLetter(source.charAt(0)) && VOWELS.indexOf(source.charAt(0)) == -1) {
                    // 「っ{元の子音}{母音}」を補ってみる
                    String[] a = concat("っ", results);
                    String[] b = results;
                    String[] c = new String[a.length + b.length];
                    System.arraycopy(a, 0, c, 0, a.length);
                    System.arraycopy(b, 0, c, a.length, b.length);
                    return c;
                } else {
                    return results;
                }
            }
        }
        return concat(source.substring(0, 1), roma2hiraDubiously(source.substring(1)));
    }

    private static String[] concat(String prefix, String[] sources) {
        return Arrays.stream(sources).map(e -> prefix + e).toArray(String[]::new);
    }

    private static String[] predictiveSearch(String key) {
        char[] stopChars = key.toCharArray();
        int lastIndex = stopChars.length - 1;
        stopChars[lastIndex] = (char)(stopChars[lastIndex] + 1);
        String stop = new String(stopChars);
        int startPos = Arrays.binarySearch(keys, key);
        if (startPos < 0) {
            startPos = -(startPos + 1);
        }
        int endPos = Arrays.binarySearch(keys, stop);
        if (endPos < 0) {
            endPos = -(endPos + 1);
        }
        return Arrays.copyOfRange(values, startPos, endPos);
    }

    private static final String[] keys = new String[] {
            "-",
            "~",
            "a",
            "ba",
            "be",
            "bi",
            "bo",
            "bu",
            "bya",
            "bye",
            "byi",
            "byo",
            "byu",
            "ca",
            "ce",
            "cha",
            "che",
            "chi",
            "cho",
            "chu",
            "ci",
            "co",
            "cu",
            "da",
            "de",
            "dha",
            "dhe",
            "dhi",
            "dho",
            "dhu",
            "di",
            "do",
            "du",
            "e",
            "fa",
            "fe",
            "fi",
            "fo",
            "fu",
            "fwa",
            "fwe",
            "fwi",
            "fwo",
            "fwu",
            "fya",
            "fye",
            "fyi",
            "fyo",
            "fyu",
            "ga",
            "ge",
            "gi",
            "go",
            "gu",
            "gwa",
            "gwe",
            "gwi",
            "gwo",
            "gwu",
            "gya",
            "gye",
            "gyi",
            "gyo",
            "gyu",
            "ha",
            "he",
            "hi",
            "ho",
            "hu",
            "hya",
            "hye",
            "hyi",
            "hyo",
            "hyu",
            "i",
            "ja",
            "je",
            "ji",
            "jo",
            "ju",
            "jya",
            "jye",
            "jyi",
            "jyo",
            "jyu",
            "ka",
            "ke",
            "ki",
            "ko",
            "ku",
            "kwa",
            "kya",
            "kye",
            "kyi",
            "kyo",
            "kyu",
            "la",
            "le",
            "li",
            "lka",
            "lke",
            "lo",
            "ltu",
            "lu",
            "lwa",
            "lya",
            "lye",
            "lyi",
            "lyo",
            "lyu",
            "ma",
            "mba",
            "mbe",
            "mbi",
            "mbo",
            "mbu",
            "me",
            "mi",
            "mma",
            "mme",
            "mmi",
            "mmo",
            "mmu",
            "mo",
            "mpa",
            "mpe",
            "mpi",
            "mpo",
            "mpu",
            "mu",
            "mya",
            "mye",
            "myi",
            "myo",
            "myu",
            "n'",
            "na",
            "ne",
            "ni",
            "nn",
            "no",
            "nu",
            "nya",
            "nye",
            "nyi",
            "nyo",
            "nyu",
            "o",
            "pa",
            "pe",
            "pi",
            "po",
            "pu",
            "pya",
            "pye",
            "pyi",
            "pyo",
            "pyu",
            "qa",
            "qe",
            "qi",
            "qo",
            "qu",
            "qwa",
            "qwe",
            "qwi",
            "qwo",
            "qwu",
            "qya",
            "qye",
            "qyi",
            "qyo",
            "qyu",
            "ra",
            "re",
            "ri",
            "ro",
            "ru",
            "rya",
            "rye",
            "ryi",
            "ryo",
            "ryu",
            "sa",
            "se",
            "sha",
            "she",
            "shi",
            "sho",
            "shu",
            "si",
            "so",
            "su",
            "swa",
            "swe",
            "swi",
            "swo",
            "swu",
            "sya",
            "sye",
            "syi",
            "syo",
            "syu",
            "ta",
            "tcha",
            "tche",
            "tchi",
            "tcho",
            "tchu",
            "te",
            "tha",
            "the",
            "thi",
            "tho",
            "thu",
            "ti",
            "to",
            "tsa",
            "tse",
            "tsi",
            "tso",
            "tsu",
            "tu",
            "twa",
            "twe",
            "twi",
            "two",
            "twu",
            "tya",
            "tye",
            "tyi",
            "tyo",
            "tyu",
            "u",
            "va",
            "ve",
            "vi",
            "vo",
            "vu",
            "vya",
            "vye",
            "vyi",
            "vyo",
            "vyu",
            "wa",
            "we",
            "wi",
            "wo",
            "wu",
            "xa",
            "xe",
            "xi",
            "xka",
            "xke",
            "xn",
            "xo",
            "xtu",
            "xu",
            "xwa",
            "xya",
            "xye",
            "xyi",
            "xyo",
            "xyu",
            "ya",
            "ye",
            "yi",
            "yo",
            "yu",
            "za",
            "ze",
            "zi",
            "zo",
            "zu",
    };

    private static final String[] values = new String[] {
            "ー",
            "～",
            "あ",
            "ば",
            "べ",
            "び",
            "ぼ",
            "ぶ",
            "びゃ",
            "びぇ",
            "びぃ",
            "びょ",
            "びゅ",
            "か",
            "せ",
            "ちゃ",
            "ちぇ",
            "ち",
            "ちょ",
            "ちゅ",
            "し",
            "こ",
            "く",
            "だ",
            "で",
            "でゃ",
            "でぇ",
            "でぃ",
            "でょ",
            "でゅ",
            "ぢ",
            "ど",
            "づ",
            "え",
            "ふぁ",
            "ふぇ",
            "ふぃ",
            "ふぉ",
            "ふ",
            "ふぁ",
            "ふぇ",
            "ふぃ",
            "ふぉ",
            "ふぅ",
            "ふゃ",
            "ふぇ",
            "ふぃ",
            "ふょ",
            "ふゅ",
            "が",
            "げ",
            "ぎ",
            "ご",
            "ぐ",
            "ぐぁ",
            "ぐぇ",
            "ぐぃ",
            "ぐぉ",
            "ぐぅ",
            "ぎゃ",
            "ぎぇ",
            "ぎぃ",
            "ぎょ",
            "ぎゅ",
            "は",
            "へ",
            "ひ",
            "ほ",
            "ふ",
            "ひゃ",
            "ひぇ",
            "ひぃ",
            "ひょ",
            "ひゅ",
            "い",
            "じゃ",
            "じぇ",
            "じ",
            "じょ",
            "じゅ",
            "じゃ",
            "じぇ",
            "じぃ",
            "じょ",
            "じゅ",
            "か",
            "け",
            "き",
            "こ",
            "く",
            "くぁ",
            "きゃ",
            "きぇ",
            "きぃ",
            "きょ",
            "きゅ",
            "ぁ",
            "ぇ",
            "ぃ",
            "ヵ",
            "ヶ",
            "ぉ",
            "っ",
            "ぅ",
            "ゎ",
            "ゃ",
            "ぇ",
            "ぃ",
            "ょ",
            "ゅ",
            "ま",
            "んば",
            "んべ",
            "んび",
            "んぼ",
            "んぶ",
            "め",
            "み",
            "んま",
            "んめ",
            "んみ",
            "んも",
            "んむ",
            "も",
            "んぱ",
            "んぺ",
            "んぴ",
            "んぽ",
            "んぷ",
            "む",
            "みゃ",
            "みぇ",
            "みぃ",
            "みょ",
            "みゅ",
            "ん",
            "な",
            "ね",
            "に",
            "ん",
            "の",
            "ぬ",
            "にゃ",
            "にぇ",
            "にぃ",
            "にょ",
            "にゅ",
            "お",
            "ぱ",
            "ぺ",
            "ぴ",
            "ぽ",
            "ぷ",
            "ぴゃ",
            "ぴぇ",
            "ぴぃ",
            "ぴょ",
            "ぴゅ",
            "くぁ",
            "くぇ",
            "くぃ",
            "くぉ",
            "く",
            "くぁ",
            "くぇ",
            "くぃ",
            "くぉ",
            "くぅ",
            "くゃ",
            "くぇ",
            "くぃ",
            "くょ",
            "くゅ",
            "ら",
            "れ",
            "り",
            "ろ",
            "る",
            "りゃ",
            "りぇ",
            "りぃ",
            "りょ",
            "りゅ",
            "さ",
            "せ",
            "しゃ",
            "しぇ",
            "し",
            "しょ",
            "しゅ",
            "し",
            "そ",
            "す",
            "すぁ",
            "すぇ",
            "すぃ",
            "すぉ",
            "すぅ",
            "しゃ",
            "しぇ",
            "しぃ",
            "しょ",
            "しゅ",
            "た",
            "っちゃ",
            "っちぇ",
            "っち",
            "っちょ",
            "っちゅ",
            "て",
            "てゃ",
            "てぇ",
            "てぃ",
            "てょ",
            "てゅ",
            "ち",
            "と",
            "つぁ",
            "つぇ",
            "つぃ",
            "つぉ",
            "つ",
            "つ",
            "とぁ",
            "とぇ",
            "とぃ",
            "とぉ",
            "とぅ",
            "ちゃ",
            "ちぇ",
            "ちぃ",
            "ちょ",
            "ちゅ",
            "う",
            "ヴぁ",
            "ヴぇ",
            "ヴぃ",
            "ヴぉ",
            "ヴ",
            "ヴゃ",
            "ヴぇ",
            "ヴぃ",
            "ヴょ",
            "ヴゅ",
            "わ",
            "ゑ",
            "ゐ",
            "を",
            "う",
            "ぁ",
            "ぇ",
            "ぃ",
            "ヵ",
            "ヶ",
            "ん",
            "ぉ",
            "っ",
            "ぅ",
            "ゎ",
            "ゃ",
            "ぇ",
            "ぃ",
            "ょ",
            "ゅ",
            "や",
            "いぇ",
            "い",
            "よ",
            "ゆ",
            "ざ",
            "ぜ",
            "じ",
            "ぞ",
            "ず",
    };
}
